name: authApi
recipe: laravel
config:
  php: 8.1
  via: nginx
  webroot: ./public
services:
  database:
    portforward: 33112
    type: mysql:8.0
  node:
    type: node:18
    scanner: false
    ports:
      - 6211:6211
tooling:
  dev:
    service: node
    cmd: npm run dev
  build:
    service: node
    cmd: npm run build
  npm:
    service: node
